version: '3.2'

services:

  mongo_express:
    image: mongo-express:latest
    container_name: docker_mongo_express
    restart: always
    ports:
      - 27018:8081
    env_file:
      - ../../.env
    environment:
      ME_CONFIG_MONGODB_SERVER: "192.168.1.9"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}