version: '3.2'

services:

  mongo:
    image: mongo:latest
    container_name: docker_mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    env_file:
      - ../../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}