version: "3.2"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: docker_mqtt
    restart: always
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 1883:1883
      - 1884:1884
      - 9001:9001
      - 9002:9002
